### ISSUE TITLE
you are dumb

### ISSUE THREAD

**Issue by polymorphiccodewillnotfixyourbrain** [cezacs1/cs-go-ezexternal---open-source-development#1]
memory.Write<int>(memory.client + signatures.dwForceAttack, 6);

**Comment by cezacs1** [comment]
Hey, i will use writeprocessmemory in this poject. Thats why i did it with dwForceAttack.

So as not to be detected (or so that you think);
u can user left click or cmd -> +attack.

I recommend that you think a little before commenting :)

**Comment by cezacs1** [comment]
Hey, i will use writeprocessmemory in this poject. Thats why i did it with dwForceAttack.

So as not to be detected (or so that you think);
u can use left click or cmd -> +attack.

I recommend that you think a little before commenting :)
